

name: PR Notifier
on:
  pull_request:
    branches: [ main ]
jobs:
  add-assigness:
    runs-on: ubuntu-latest
    steps:
      - name: Work Weixin Notifier
        uses: jerray/work-weixin-notifier@v1.1.0
        with:
          key: ${{ secrets.weixin_bot_key }}
          content: '**【NodeSDK】**`PR`有更新(${{github.event.pull_request.state}})，请关注@ostwindli@shaohuizuo [${{github.event.pull_request.html_url}}](${{github.event.pull_request.html_url}}) '
          type: markdown
          status: ${{ job.status }}
